### ISSUE TITLE
Something is up with the main JS file in level one.

### ISSUE THREAD

**Issue by thaStevester** [thaStevester/CAB_PROJECT#2]
Can't display any text or images on the first scenario -- all other scenarios work fine. It's just this one. Probably syntax...

**Comment by abc123me** [comment]
Ill look into it

**Comment by thaStevester** [comment]
It has nothing to do with the declaration of the scenario in the dictionary... I changed the advanceTo on the onbuttondown event to change from splash page to one, and every image and string rendered as expected. It must have something to do w/ the recently introduced link attached to a pic.

**Comment by thaStevester** [comment]
I don't know man. I couldn't find the error. Might need to clean up some of the funcs and vars that aren't being used yet so we can fin the problem quicker. 
[CAB_PROJECT-master.zip](https://github.com/thaStevester/CAB_PROJECT/files/702022/CAB_PROJECT-master.zip)

**Comment by abc123me** [comment]
Sounds good im currently looking into some script engines for Java like Jython, so we can run python server-side which may be helpful

**Comment by thaStevester** [comment]
The problem is definitely in the dictionary. 
`var scenario = {}

scenario = {
	one: {
		image: "Python  - trans.png",
		text: "Welcome to Coding Across Borders! Enter your name below to begin."
	},
	two: {
		image: "http://i66.tinypic.com/v6j2wn.png",
		text: "Throughout this course, you will learn a little about some of the concepts used to create programs like the one you're using right now.",
		buttons: [
            [ "Continue", "advanceTo(scenario.three)" ]
        ]
	},
	three: {
		image: "http://i68.tinypic.com/25flgg6.png",
		text: "In order to complete this program, you will be asked to respond using the controls below.",
		buttons: [
            [ "Continue", "advanceTo(scenario.four)" ]
        ]
	},
	four: {
		image: "//Don't Have This Yet",
		text: "Periodically, you will be asked to try it yourself. To do this, click on the image of the Coding Across Borders Try It Yourself Editor in the top left corner (go ahead and open this now). ",
		buttons: [
            [ "Continue", "advanceTo(scenario.six)" ]
            , [ "Exit", "advanceTo(scenario.two)" ]
        ]
	},
	five: {
		image: "//img",
		text: "Hi! This is Coding Across Borders level one. Here, you will get your feet wet in a prgramming language known as 'Python'.",
		buttons: [
            [ "Continue", "advanceTo(scenario.six)" ]
        ]
	},
	six: {
		image: "//img",
		text: "Python is an object-based language that is used to make things like video-games.",
		buttons: [
            [ "Continue", "advanceTo(scenario.seven)" ]
        ]
	},
	seven: {
		image: "//img",
		text: "By the end of this course, you will be able to create a really cool program with turtle!",
		buttons: [
            [ "Continue", "advanceTo(scenario.eight)" ]
        ]
	},
	eight: {
		image: "//img",
		text: "In order to start, we must first tell the computer to get the turtle. Do this by typing the line 'import turtle' without quotes in the first line of the Try It Yourself editor.",
		buttons: [
            [ "Continue", "advanceTo(scenario.nine)" ]
        ]
	},
	nine: {
		image: "//img",
		text: "Import tells Python to get some code to do a specific things. Another example we'll get to later in this module is 'math'.",
		buttons: [
            [ "Continue", "advanceTo(scenario.ten)" ]
        ]
	},
	ten: {
		image: "//img",
		text: "What does 'import' do in Python?",
		buttons: [
            [ "Tells Python to get some code to do a specific thing", "advanceTo(scenario.eleven)" ]
            , [ "Tells Python to just get the turtle", "advanceTo(scenario.twelve)" ]
        ]
	},
	eleven: {
		image: "//img",
		text: "Correct! Import is useful for so many different things.",
		buttons: [
            [ "Continue", "advanceTo(scenario.thirteen)" ]
        ]
	},
	twelve: {
		image: "//img",
		text: "Incorrect!",
		buttons: [
            [ "Continue", "advanceTo(scenario.ten)" ]
        ]
	},
	thirteen: {
		image: "//img",
		text: "Now we have a turtle, but he has no home! Let's make him a nice home.",
		buttons: [
            [ "Continue", "advanceTo(scenario.fourteen)" ]
        ]
	},
	fourteen: {
		image: "//img",
		text: "In order to give the turtle a home, we need to make a variable for it. A variable is something that stores something else. An example is 'age = 10'. In this case, age is a variable, and 10 is what it represents.",
		buttons: [
            [ "Continue", "advanceTo(scenario.fifteen)" ]
        ]
	},
	fifteen: {
		image: "//img",
		text: "What does a variable do?",
		buttons: [
            [ "Store things", "advanceTo(scenario.sixteen)" ]
            , [ "Makes Python a scripting language", "advanceTo(scenario.seventeen)" ]
        ]
	},
	sixteen: {
		image: "//img",
		text: "Correct! Python does a great job at helping us store things that we can use over and over again.",
		buttons: [
            [ "Continue", "advanceTo(scenario.eighteen)" ]
        ]
	},
	seventeen: {
		image: "//img",
		text: "Incorrect! Try again.",
		buttons: [
            [ "Continue", "advanceTo(scenario.fifteen)" ]
        ]
	},
};`

**Comment by thaStevester** [comment]
I'm pretty sure this issue just comes up on school computers...

**Comment by abc123me** [comment]
This is very far fetched and I think languages like JavaScript are immune to this but could it be because you dont have a buttons value in it?
`one: {
     image: "Python - trans.png",
     text: "Welcome to Coding Across Borders! Enter your name below to begin."
},
two: {
     image: "http://i66.tinypic.com/v6j2wn.png",
     text: "Throughout this course, you will learn a little about some of the concepts used to create programs                           like the one you're using right now.",
     buttons: [
     [ "Continue", "advanceTo(scenario.three)" ]
     ]
},`

**Comment by abc123me** [comment]
Since it only appears on school computers could it be because of the **http://i66.tinypic.com/v6j2wn.png** url there because if its blocked then it obviously wont show and that could be breaking something else in the code

**Comment by abc123me** [comment]
Maybe the schools custom ISP is blocking the image site
