### ISSUE TITLE
Server side code execution

### ISSUE THREAD

**Issue by abc123me** [thaStevester/CAB_PROJECT#3]
I could easily implement server-side Python, Mozilla EMCA script, Perl which could be very useful for login systems etc.

**Comment by thaStevester** [comment]
Sounds good. I don't know what we're gonna do with a login function at this point, but I'm sure that it'll be helpful at some point. Go ahead and start that in the "Projects" of git hub.

**Comment by abc123me** [comment]
login function would be easily implementable via PHP which is already implemented right now im speed-learning php and so far I got all the basics down all i would have to learn is sql and php sql
